{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codeq.fullname" . }}-secrets
  labels:
{{ include "codeq.labels" . | indent 4 }}
type: Opaque
data:
  identityServiceApiKey: {{ .Values.secrets.identityServiceApiKey | b64enc | quote }}
  webhookHmacSecret: {{ .Values.secrets.webhookHmacSecret | b64enc | quote }}
{{- end }}
