apiVersion: v1
kind: Service
metadata:
  name: {{ include "codeq.fullname" . }}
  labels:
{{ include "codeq.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app.kubernetes.io/name: {{ include "codeq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
